spring:
  application:
    name: devscribe-notes-app
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:notesdb
    username: admin
    password: admin
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database: h2
    hibernate:
      ddl-auto: create
    show-sql: true